site_name: sso-0.11.0
site_url: https://mojzu.net/sso/
repo_url: https://github.com/mojzu/sso
site_author: "Sam Ward"
copyright: Unlicense
docs_dir: sso_manual
site_dir: docs
dev_addr: 0.0.0.0:8079
nav:
  - index.md
  - User:
    - user/start.md
  - Developer:
    - developer/start.md
    - developer/tasks.md
theme: readthedocs
