version: "3"
services:
  build-postgres:
    build:
      context: postgres
      dockerfile: dockerfile
    image: sso-build/postgres:latest
    restart: "no"
    entrypoint: ["echo", "sso-build/postgres image"]

  build-mkdocs:
    build:
      context: mkdocs
      dockerfile: dockerfile
    image: sso-build/mkdocs:latest
    restart: "no"
    entrypoint: ["echo", "sso-build/mkdocs image"]

  build-prometheus:
    build:
      context: prometheus
      dockerfile: dockerfile
    image: sso-build/prometheus:latest
    restart: "no"
    entrypoint: ["echo", "sso-build/prometheus image"]

  build:
    build:
      context: ..
      dockerfile: .devcontainer/build/build.dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    image: sso-build:latest
    restart: "no"
    entrypoint: ["echo", "sso-build image"]

  build-cache-rust:
    build:
      context: ..
      dockerfile: .devcontainer/build/cache-rust.dockerfile
    image: sso-build/cache-rust:latest
    restart: "no"
    entrypoint: ["echo", "sso-build/cache-rust image"]

  build-cache-node:
    build:
      context: ..
      dockerfile: .devcontainer/build/cache-node.dockerfile
    image: sso-build/cache-node:latest
    restart: "no"
    entrypoint: ["echo", "sso-build/cache-node image"]

  build-test:
    build:
      context: ..
      dockerfile: .devcontainer/build/test.dockerfile
    image: sso-build/test:latest
    restart: "no"
    depends_on:
      - build-cache-node
    entrypoint: ["echo", "sso-build/test image"]

  build-sso:
    build:
      context: ..
      dockerfile: .devcontainer/build/sso.dockerfile
    image: sso-build/sso:latest
    restart: "no"
    depends_on:
      - build-cache-rust
    entrypoint: ["echo", "sso-build/sso image"]
