version: "3"
services:
  postgres:
    image: sso-build/postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432

  sso:
    build:
      context: ..
      dockerfile: .devcontainer/test/sso.dockerfile
    image: sso-build/test-sso:latest
    restart: unless-stopped
    environment:
      RUST_BACKTRACE: "1"
      RUST_LOG: "sso=info,sso_server=info"
    ports:
      - 7042:7042
      - 7043:7043
    volumes:
      - "mailto:/config/mailto"
    depends_on:
      - postgres
    entrypoint: ["/wait-for-it.sh", "postgres:5432"]
    command: ["--", "sso_server", "--config", "sso"]

  client:
    image: sso-build/test:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - sso
    entrypoint: ["/wait-for-it.sh", "sso:7042"]
    command: ["--", "node", "/opt/sso_test/tmp/example/express-passport-docker.js"]

  postgres2:
    image: sso-build/postgres:latest
    restart: unless-stopped
    ports:
      - 5433:5432

  sso2:
    build:
      context: ..
      dockerfile: .devcontainer/test/sso2.dockerfile
    image: sso-build/test-sso2:latest
    restart: unless-stopped
    environment:
      RUST_BACKTRACE: "1"
      RUST_LOG: "sso=info,sso_server=info"
    ports:
      - 7044:7042
      - 7045:7043
    depends_on:
      - postgres2
    entrypoint: ["/wait-for-it.sh", "postgres2:5432"]
    command: ["--", "sso_server", "--config", "sso"]

  protractor:
    image: sso-build/test:latest
    restart: "no"
    network_mode: "host"
    volumes:
      - "mailto:/opt/mailto"
    depends_on:
      - client
    entrypoint: ["/wait-for-it.sh", "client:8080"]
    command: ["--", "echo", "ready to run protractor tests task"]

volumes:
  mailto:
