version: "3"
services:
  build-postgres:
    build:
      context: postgres
      dockerfile: dockerfile
    image: sso/build-postgres:latest
    restart: "no"
    entrypoint: ["echo", "sso/build-postgres image"]

  build-mkdocs:
    build:
      context: mkdocs
      dockerfile: dockerfile
    image: sso/build-mkdocs:latest
    restart: "no"
    entrypoint: ["echo", "sso/build-mkdocs image"]

  build:
    build:
      context: ..
      dockerfile: .devcontainer/build/build.dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    image: sso/build:latest
    restart: "no"
    entrypoint: ["echo", "sso/build image"]

  build-cache:
    build:
      context: ..
      dockerfile: .devcontainer/build/cache.dockerfile
    image: sso/build-cache:latest
    restart: "no"
    entrypoint: ["echo", "sso/build-cache image"]

  build-release:
    build:
      context: ..
      dockerfile: .devcontainer/build/release.dockerfile
    image: sso/build-release:latest
    restart: "no"
    entrypoint: ["echo", "sso/build-release image"]

  build-test:
    build:
      context: ..
      dockerfile: .devcontainer/build/test.dockerfile
    image: sso/build-test:latest
    restart: "no"
    entrypoint: ["echo", "sso/build-test image"]

  build-sso:
    build:
      context: ..
      dockerfile: .devcontainer/build/sso.dockerfile
    image: sso/sso:latest
    restart: "no"
    entrypoint: ["echo", "sso/sso image"]
