version: "3"
services:
  selenium:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20200921
    ports:
      - "4442:4442"
      - "4443:4443"
      - "6444:4444"

  selenium-chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200921
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-firefox:
    image: selenium/node-firefox:4.0.0-alpha-7-prerelease-20200921
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"
