name: Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: sso

# todo: Docker compose tests run here and image publishing?

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
