name: Docker CI

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: sso

# todo: Docker image publish/push to registry here

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker-compose -f .devcontainer/docker-build.yml build build-cache-rust build-sso build-cache-node build-test
          docker-compose -f .devcontainer/docker-test-ci.yml build
          docker-compose -f .devcontainer/docker-test-ci.yml up -d
          sleep 15
          docker-compose -f .devcontainer/docker-test-ci.yml -f .devcontainer/docker-test-ci-sut.yml run sut

  build:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker-compose -f .devcontainer/docker-build.yml build build-cache-rust build-sso
          docker tag sso-build/sso:latest $IMAGE_NAME
