name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all -- -D warnings

# todo: Enable these when compilation under 1.46 is fixed
# - name: Build
#   run: cargo build --verbose
# - name: Test
#   run: cargo test --verbose

# todo: Cargo audit CI, would this be useful? Points to dependencies of dependencies
# - name: Audit
#   run: cargo audit --deny-warnings
