name: Rust CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # todo: Remove this step when compilation under latest stable (1.47) is fixed
      - name: Rust 1.45.2
        run: |
          rustup toolchain install 1.45.2
          rustup default 1.45.2
          rustup component add rustfmt rls clippy

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

# todo: Cargo audit CI, would this be useful? Points to dependencies of dependencies
# - name: Audit
#   run: cargo audit --deny-warnings
