name: Rust CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Rust 1.48.0
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.48.0
            default: true
            components: rustfmt, clippy

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      # fix: Allow warnings while this points to dependencies of dependencies
      # Add `--deny-warnings` flag at some point
      - name: Audit
        run: cargo audit
